name: codebase checks

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      COMPOSER_NO_INTERACTION: 1

    strategy:
      matrix:
        php: ["8.3", "8.2", "8.1", "8.0", "7.4"]

    name: PHP ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer, phpcpd, phpmd, phpunit:9.6, php-cs-fixer, phpstan

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress

      - name: Run phpstan
        run: phpstan

      - name: Run PHPUnit
        run: phpunit --verbose

      - name: Run phpmd
        run: |
          phpmd src xml codesize,unusedcode,naming,design
          phpmd tests xml codesize,unusedcode,naming,design

      - name: Run phpcpd
        run: |
          phpcpd src
          phpcpd tests

      - name: Run php-cs-fixer
        run: |
          php-cs-fixer fix src --diff --dry-run -v --rules=@Symfony
          php-cs-fixer fix tests --diff --dry-run -v --rules=@Symfony
